name: binary-testing
on : [push]
jobs:
  compiling:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: /app

    steps:
      - env: 
          MY_VAR: ${{ github.action_path }}
        run: echo MY_VAR
      - run: ls -l
      - run: make re
