name: binary-testing
on : [push]
jobs:
  compiling:
    runs-on: ubuntu-latest
    steps:
      - run: ls -l
      - run: cd ../..
      - run: ls -l
      - run: make re
  
  execution:
    runs-on: ubuntu-latest
    steps:
      - run: ls -l
      - run: cd ../..
      - run: ls -l
      - run: ./a.out 42
