name: binary-testing
run-name: basic binary-testing
on : [push]
jobs:
  compiling:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: checkout
        uses: "actions/checkout@v3"
      - run: make re
      - run: ./a.out 42
      - run: echo $?
