name: binary-testing
on : [push]
jobs:
  compiling:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: /

    steps:
      - run: pwd
      - name: checkout
        uses: "actions/checkout@v3"
      - run: pwd
      - run: ls -l
      - run: make re
