name: binary-testing
on : [push]
jobs:
  compiling:
    runs-on: ubuntu-latest
    steps:
      - echo: ${{ github.action_path }}
      - run: cd ${{ github.action_path }}
      - run: ls -l
      - run: make re
  
  execution:
    runs-on: ubuntu-latest
    steps:
      - run: cd ${{ github.action_path }} 
      - run: ls -l
      - run: ./a.out 42
