name: learn-github-actions
run-name: [ ${{ github.event_name }} ], ${{ github.triggering_actor }} triggered this workflow on repo ${{ github.repository }} . #Owner and repo name of the action: ${{ github.action_repository }} . 
on : [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
      - run: ls -la
      - run: echo "Golgoth\n"

name: learn-github-actions2
run-name:  ${{ github.triggering_actor }} did a [ ${{ github.event_name }} ]
on : [pull]
jobs:
  compile_test:
    runs-on: ubuntu-latest
    step:
      - run: make re
      - run: ./a.out 255
      - run: echo $?
