name: learn-github-actions
run-name: ::${{ github.event_name }}:: by ${{ github.triggering_actor }}. #Owner and repo name of the action: ${{ github.action_repository }} . 
on : [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
      - run: ls -la
      - run: echo "Golgoth\n"

